import Head from 'next/head'
import Header from '../../components/Header'


export default function Home() {
  return (
    <div className='lg:mx-[90px]'>
      <Head>
        <title>Desmond Fon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}
