import Head from 'next/head';
import Nav from '../../components/Nav';
import Header from '../../components/Header';
import Image from 'next/image';
import Link from 'next/link';
import About from '../../components/About';
// import Dez from '../../public/images/dez.JPG';



export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Desmond Fon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <About />
    </div>
  )
}
